In [2]:
import numpy as np
np.__version__

'1.26.4'

In [9]:
po1=np.arange(5)**2
po2=np.arange(5)**3
w=po2+po1
w.

1

In [4]:
# 创建numpy数组
x=np.array([1,2,3,4,5,6,7])
type(x)


numpy.ndarray

In [16]:
#创建一个维数组里面有5个随机数
np.random.randn(5)
# 创建一个5x3的随机矩阵
np.random.randn(5,3)
# 拆分
w=np.arange(10).reshape(2,5)
w.shape

AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [6]:
list_my_small=np.arange(10)
list_my_small[2]
list_my=np.arange(10).reshape(2,5)
list_my[1][1]+=1
list_my

array([[0, 1, 2, 3, 4],
       [5, 7, 7, 8, 9]])

In [7]:
#查看最大索引
max_my=np.random.randint(10,100,10)
print(max_my)
# 返回的是最大值的索引意思是排序后的值从小到大
max_my.argsort()
# 返回最大值
max_my[max_my.argsort()[-3:]]

[47 97 92 38 68 30 70 65 43 84]


array([84, 92, 97])